### ISSUE TITLE
Generate Password contain double quotes (") and backslash (\)

### ISSUE THREAD

**Issue by Kaustubh-pande** [sethvargo/go-password#10]
In most of the case password not accept double-quotes (") and backslash (\) but Generate password function generate these symbols.
Need to remove these from generate.go.

**Comment by sethvargo** [comment]
You can customize the list of letters, symbols, numbers, etc. Create a new generator object and alter the list of symbols to be a string of the allowed symbols (e.g. `"!@#$%^&*()"`) and it will only generate from those symbols. 

```go
gen, err := password.NewGenerator(&password.NewGeneratorInput{
  Symbols: "PUT YOUR LIST OF SYMBOLS HERE AS A SINGLE STRING",
})
if err != nil {
  # ...
}

gen.Generate(...)
```

**Comment by Kaustubh-pande** [comment]
Sorry, my bad...
I used your example from README.
Just for a suggestion, you can add these in README it will be more helpful.

**Comment by sethvargo** [comment]
Hi @Kaustubh-pande it's in the [godoc](https://godoc.org/github.com/sethvargo/go-password/password#NewGenerator)
