### ISSUE TITLE
Go toolchain use

### ISSUE THREAD

**Issue by matthewhartstonge** [sethvargo/go-password#27]
Hi Seth!

I'm curious on the jump to `go@1.22` for `v0.3.0` - I've noticed my builds failing as the `toolchain` command forces our `go@1.21` builds to install and build with `go@1.22`.

Is `go@1.22` required or would `go@1.21` be enough to match Go's n-1 support?

**Comment by sethvargo** [comment]
v0.3.1

**Comment by matthewhartstonge** [comment]
You're a rocket ship!! 🚀

Thanks! 🙏
