### ISSUE TITLE
Ability to override symbols seed

### ISSUE THREAD

**Issue by rendicott** [sethvargo/go-password#3]
Lots of things don't allow all symbols (e.g., AWS IAM). It would be nice if the password.Symbols wasn't a constant so I can override it with my own valid symbol set.

**Comment by sethvargo** [comment]
I could switch it to a variable, but then you have global state. I guess I'm indifferent. I don't think there's much of a performance implication, but I worry it could be a security hole. Someone could set that to the empty string...

**Comment by rendicott** [comment]
Thanks, your way is much better.
