### ISSUE TITLE
Wrong password

### ISSUE THREAD

**Issue by pashok2398** [sethvargo/go-password#8]
In some cases got "wrong" passwords like:
```
	passwd, err := password.Generate(16, 8, 8, false, false)
	if err != nil {
		log.Fatal(err)
	}
	log.Printf(passwd)
```
```
,48_$<723^05*=6%!(NOVERB)
```
```
?)~437\9}+%!&(MISSING)0618
```
```
239/1~%!,(BADINDEX)7_4{^06
```
Solved this by removing the `%` symbol from `generate.go`

**Comment by sethvargo** [comment]
Don't use `printf` since it expects `%` as a formatting call. Use `printf` instead of do raw string concatenation.

**Comment by pashok2398** [comment]
Sorry my bad...
I used your example from README and saw this problem.
Thank you .
